name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Update system
      run: sudo apt update -y
    - name: Install libev
      run: sudo apt install -y libev4 libev-dev
    - name: Install cJSON
      run: sudo apt install -y libcjson1 libcjson-dev
    - name: Install systemd
      run: sudo apt install -y libsystemd-dev
    - name: Install rst2man
      run: sudo apt install -y python3-docutils
    - name: Install clang
      run: sudo apt install -y clang
    - name: GCC/mkdir
      run: mkdir build
      working-directory: /home/runner/work/pgagroal/pgagroal/
    - name: GCC/cmake
      run: export CC=/usr/bin/gcc && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /home/runner/work/pgagroal/pgagroal/build/
    - name: GCC/make
      run: make
      working-directory: /home/runner/work/pgagroal/pgagroal/build/
    - name: rm -Rf
      run: rm -Rf build/
      working-directory: /home/runner/work/pgagroal/pgagroal/
    - name: CLANG/mkdir
      run: mkdir build
      working-directory: /home/runner/work/pgagroal/pgagroal/
    - name: CLANG/cmake
      run: export CC=/usr/bin/clang && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /home/runner/work/pgagroal/pgagroal/build/
    - name: CLANG/make
      run: make
      working-directory: /home/runner/work/pgagroal/pgagroal/build/



  build-macos:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Update system
      run: brew update
    - name: Install openssl
      run: brew install openssl
    - name: Install libev
      run: brew install libev
    - name: Install cJSON
      run: brew install cjson
    - name: Install rst2man
      run: brew install docutils
    - name: Install clang
      run: brew install llvm
    - name: GCC/mkdir
      run: mkdir build
      working-directory: /Users/runner/work/pgagroal/pgagroal/
    - name: GCC/cmake
      run: export CC=/usr/bin/gcc && export OPENSSL_ROOT_DIR=`brew --prefix openssl` && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /Users/runner/work/pgagroal/pgagroal/build/
    - name: GCC/make
      run: make
      working-directory: /Users/runner/work/pgagroal/pgagroal/build/
    - name: rm -Rf
      run: rm -Rf build/
      working-directory: /Users/runner/work/pgagroal/pgagroal/
    - name: CLANG/mkdir
      run: mkdir build
      working-directory: /Users/runner/work/pgagroal/pgagroal/
    - name: CLANG/cmake
      run: export CC=/usr/bin/clang && export OPENSSL_ROOT_DIR=`brew --prefix openssl` && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /Users/runner/work/pgagroal/pgagroal/build/
    - name: CLANG/make
      run: make
      working-directory: /Users/runner/work/pgagroal/pgagroal/build/
